apiVersion: v1
kind: Secret
metadata:
  name: gitlab-regcred
  namespace: r-mlops-k8s-12-1-1-854415502
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "mlops.gitlab.yandexcloud.net:5050": {
          "username": "for_k8s",
          "password": "***"
        }
      }
    }