apiVersion: v1
kind: Service
metadata:
  name: simonov-inference-service
  namespace: r-mlops-k8s-12-1-1-854415502
spec:
  type: ClusterIP
  selector:
    app: simonov-inference
  ports:
    - name: http
      port: 80
      targetPort: 32000
      protocol: TCP