apiVersion: v1
kind: Secret
metadata:
  name: simonov-secret
  namespace: r-mlops-k8s-9-1-3-854415502
  annotations:
    serving.kserve.io/s3-endpoint: storage.yandexcloud.net:443
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-verifyssl: "1"
    serving.kserve.io/s3-region: "ru-central1"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "***" # здесь укажите access_key
  AWS_SECRET_ACCESS_KEY: "***" # здесь укажите secret_key