apiVersion: 1
datasources:
  - name: Prometheus # типовое название
    type: prometheus # тип базы данных - источника
    access: proxy
    url: http://prometheus:9090 # адрес базы данных
    uid: prometheus # uid для работы с бд (нужен для дашборда)
    isDefault: true
