{
 "title": "infra_dashbord_basic Copy",
 "description": "Для обучения работы с cAdvisor + Prometheus + Grafana -> MLOps (модуль по мониторингу)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Network Traffic (Inbound + Outbound)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total[1m]) / (1024^2)\n",
     "legendFormat": "{{interface}} IN"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total[1m]) / (1024^2)\n",
     "legendFormat": "{{interface}} OUT"
    }
   ]
  },
  {
   "title": "CPU usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service!=\"\"}[1m]) * 100",
     "legendFormat": "{{container_label_com_docker_compose_service}} CPU"
    }
   ]
  },
  {
   "title": "RAM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service!=\"\"} / (1024^2)",
     "legendFormat": "{{container_label_com_docker_compose_service}} RAM"
    }
   ]
  },
  {
   "title": "IOPS Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service) (\n  rate(container_fs_reads_total{container_label_com_docker_compose_service!=\"\"}[1m]) + \n  rate(container_fs_writes_total{container_label_com_docker_compose_service!=\"\"}[1m])\n)\n",
     "legendFormat": "{{container_label_com_docker_compose_service}} IOPS"
    }
   ]
  }
 ]
}